modbusmonitor:
  netbox_token: "<NETBOX_TOKEN>"
  tg_bot_token: "<TG_BOT_TOKEN>"
  chat_id: "<CHAT_ID>"
  base_url: "<UTL_NETBOX>"
  modbus_port: 502
  message_fail: "Не відповідає"
  message_success: "Знову відповідає"
  delay: 600